config/routes.rb
Rails.application.routes.draw do
  resources :thumbs

  resources :logos

  root :to => 'welcome#index'
  get 'welcome' => 'welcome#index'

  resources :logos

end

app/models/logo.rb
class Logo < ActiveRecord::Base
end

app/models/thumb.rb
class Thumb < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logos_controller.rb
class LogosController < ApplicationController
  before_action :set_logo, only: [:show, :edit, :update, :destroy]

  # GET /logos
  # GET /logos.json
  def index
    @logos = Logo.all
  end

  # GET /logos/1
  # GET /logos/1.json
  def show
  end

  # GET /logos/new
  def new
    @logo = Logo.new
  end

  # GET /logos/1/edit
  def edit
  end

  # POST /logos
  # POST /logos.json
  def create
    @logo = Logo.new(logo_params)

    respond_to do |format|
      if @logo.save
        format.html { redirect_to @logo, notice: 'Logo was successfully created.' }
        format.json { render :show, status: :created, location: @logo }
      else
        format.html { render :new }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logos/1
  # PATCH/PUT /logos/1.json
  def update
    respond_to do |format|
      if @logo.update(logo_params)
        format.html { redirect_to @logo, notice: 'Logo was successfully updated.' }
        format.json { render :show, status: :ok, location: @logo }
      else
        format.html { render :edit }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logos/1
  # DELETE /logos/1.json
  def destroy
    @logo.destroy
    respond_to do |format|
      format.html { redirect_to logos_url, notice: 'Logo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_logo
      @logo = Logo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def logo_params
      params.require(:logo).permit(:name, :svg_url, :png_url, :jpg_url)
    end
end

app/controllers/thumbs_controller.rb
class ThumbsController < ApplicationController
  before_action :set_thumb, only: [:show, :edit, :update, :destroy]

  # GET /thumbs
  # GET /thumbs.json
  def index
    @thumbs = Thumb.all
  end

  # GET /thumbs/1
  # GET /thumbs/1.json
  def show
  end

  # GET /thumbs/new
  def new
    @thumb = Thumb.new
  end

  # GET /thumbs/1/edit
  def edit
  end

  # POST /thumbs
  # POST /thumbs.json
  def create
    @thumb = Thumb.new(thumb_params)

    respond_to do |format|
      if @thumb.save
        format.html { redirect_to @thumb, notice: 'Thumb was successfully created.' }
        format.json { render :show, status: :created, location: @thumb }
      else
        format.html { render :new }
        format.json { render json: @thumb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thumbs/1
  # PATCH/PUT /thumbs/1.json
  def update
    respond_to do |format|
      if @thumb.update(thumb_params)
        format.html { redirect_to @thumb, notice: 'Thumb was successfully updated.' }
        format.json { render :show, status: :ok, location: @thumb }
      else
        format.html { render :edit }
        format.json { render json: @thumb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thumbs/1
  # DELETE /thumbs/1.json
  def destroy
    @thumb.destroy
    respond_to do |format|
      format.html { redirect_to thumbs_url, notice: 'Thumb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thumb
      @thumb = Thumb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thumb_params
      params.require(:thumb).permit(:name, :ext, :width, :height)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @logos = Logo.all
    @thumbs = Thumb.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/helpers/thumbs_helper.rb
module ThumbsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kkblogo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logos/_form.html.erb
<%= form_for(@logo) do |f| %>
  <% if @logo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@logo.errors.count, "error") %> prohibited this logo from being saved:</h2>

      <ul>
      <% @logo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :svg_url %><br>
    <%= f.text_field :svg_url %>
  </div>
  <div class="field">
    <%= f.label :png_url %><br>
    <%= f.text_field :png_url %>
  </div>
  <div class="field">
    <%= f.label :jpg_url %><br>
    <%= f.text_field :jpg_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logos/edit.html.erb
<h1>Editing logo</h1>

<%= render 'form' %>

<%= link_to 'Show', @logo %> |
<%= link_to 'Back', logos_path %>

app/views/logos/index.html.erb
<h1>Listing logos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Svg url</th>
      <th>Png url</th>
      <th>Jpg url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logos.each do |logo| %>
      <tr>
        <td><%= logo.name %></td>
        <td><%= logo.svg_url %></td>
        <td><%= logo.png_url %></td>
        <td><%= logo.jpg_url %></td>
        <td><%= link_to 'Show', logo %></td>
        <td><%= link_to 'Edit', edit_logo_path(logo) %></td>
        <td><%= link_to 'Destroy', logo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Logo', new_logo_path %>

app/views/logos/new.html.erb
<h1>New logo</h1>

<%= render 'form' %>

<%= link_to 'Back', logos_path %>

app/views/logos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @logo.name %>
</p>

<p>
  <strong>Svg url:</strong>
  <%= @logo.svg_url %>
</p>

<p>
  <strong>Png url:</strong>
  <%= @logo.png_url %>
</p>

<p>
  <strong>Jpg url:</strong>
  <%= @logo.jpg_url %>
</p>

<%= link_to 'Edit', edit_logo_path(@logo) %> |
<%= link_to 'Back', logos_path %>

app/views/thumbs/_form.html.erb
<%= form_for(@thumb) do |f| %>
  <% if @thumb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thumb.errors.count, "error") %> prohibited this thumb from being saved:</h2>

      <ul>
      <% @thumb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ext %><br>
    <%= f.text_field :ext %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.number_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thumbs/edit.html.erb
<h1>Editing thumb</h1>

<%= render 'form' %>

<%= link_to 'Show', @thumb %> |
<%= link_to 'Back', thumbs_path %>

app/views/thumbs/index.html.erb
<h1>Listing thumbs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ext</th>
      <th>Width</th>
      <th>Height</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thumbs.each do |thumb| %>
      <tr>
        <td><%= thumb.name %></td>
        <td><%= thumb.ext %></td>
        <td><%= thumb.width %></td>
        <td><%= thumb.height %></td>
        <td><%= link_to 'Show', thumb %></td>
        <td><%= link_to 'Edit', edit_thumb_path(thumb) %></td>
        <td><%= link_to 'Destroy', thumb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thumb', new_thumb_path %>

app/views/thumbs/new.html.erb
<h1>New thumb</h1>

<%= render 'form' %>

<%= link_to 'Back', thumbs_path %>

app/views/thumbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thumb.name %>
</p>

<p>
  <strong>Ext:</strong>
  <%= @thumb.ext %>
</p>

<p>
  <strong>Width:</strong>
  <%= @thumb.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @thumb.height %>
</p>

<%= link_to 'Edit', edit_thumb_path(@thumb) %> |
<%= link_to 'Back', thumbs_path %>

app/views/welcome/index.html.erb
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="favicon.ico">

  <!-- 新 Bootstrap 核心 CSS 文件 -->
  <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Custom styles for this template -->
  <!--<link href="navbar-fixed-top.css" rel="stylesheet">-->
  <!--<%= stylesheet_link_tag    "navbar-fixed-top" %>-->

  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <script src="ie-emulation-modes-warning.js"></script>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">KKB Logos</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <!-- <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li> -->
        <!--
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">WWW/CMS <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class="dropdown-header">All New</li>
            <li><a href="newkkb" target="_blank">newkkb</a></li>
            <li><a href="kkb-cms" target="_blank">kkb-cms</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">History</li>
            <li><a href="cms" target="_blank">cms</a></li>
            <li><a href="100day-start" target="_blank">100day-start</a></li>
            <li><a href="cms-grap-user-info" target="_blank">cms-grap-user-info</a></li>
            <li><a href="landing_page_for_s_class" target="_blank">landing_page_for_s_class</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">LMS <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="lms" target="_blank">lms</a></li>
            <li><a href="kkb-cms" target="_blank">kkb-cms</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">LCMS <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="lcms" target="_blank">lcms</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mobile <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class="dropdown-header">All New</li>
            <li><a href="phone" target="_blank">phone</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">History</li>
            <li><a href="tv-box" target="_blank">tv-box</a></li>
            <li><a href="tablet1.3" target="_blank">tablet1.3</a></li>
            <li><a href="kkb-phone" target="_blank">kkb-phone</a></li>
            <li><a href="ipad1.0" target="_blank">ipad1.0</a></li>
            <li><a href="ipad1.2" target="_blank">ipad1.2</a></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">ZZR <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="zzr" target="_blank">zzr</a></li>
          </ul>
        </li>
                -->
      </ul>
      <!--
      <ul class="nav navbar-nav navbar-right">
        <li><a href="../navbar/">Default</a></li>
        <li><a href="../navbar-static-top/">Static top</a></li>
        <li class="active"><a href="./">Fixed top</a></li>
      </ul>
        -->
    </div><!--/.nav-collapse -->
  </div>
</div>


<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>开课吧 Logos</h1>
    <p>&nbsp</p>
    <p>&nbsp</p>
    <!--
    <p>⬆️⬆️⬆️全部的原型，请见顶部导航⬆️⬆️⬆️</p>
    <p>⬇️⬇️⬇️常用的原型，请见首页列表⬇️⬇️⬇️</p>

    <p>
      <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
        </p>
          -->
  </div>
</div>

<div class="container">

  <% @logos.each do |logo| %>
    <div class="row">
      <h2><img src="<%= logo.png_url + '!md' %>" style="width: auto; height: auto;">
        <small><a class="btn btn-default" href="<%= logo.svg_url %>" role="button" target="_blank">下载SVG &raquo;</a></small>
      </h2>

      <hr style="height:1px;border:none;border-top:1px dashed #0066CC; margin-top: -10px;" />
      <div class="table">
        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th class="hidden-xs">ID</th>
            <th>Name</th>
            <th class="hidden-xs">Ext</th>
            <th class="hidden-xs">Width</th>
            <th class="hidden-xs">Height</th>
            <th></th>
          </tr>
          </thead>

          <% @thumbs.each do |thumb| %>
            <tr>
              <td class="hidden-xs"><%= thumb.id %></td>
              <td><%= thumb.name %></td>
              <td class="hidden-xs"><%= thumb.ext %></td>
              <% if thumb.width == -1 %>
                <td class="hidden-xs">宽度自适应</td>
              <% else %>
                <td class="hidden-xs"><%= thumb.width %>px</td>
              <% end %>
              <% if thumb.height == -1 %>
                <td class="hidden-xs">高度自适应</td>
              <% else %>
                <td class="hidden-xs"><%= thumb.height %>px</td>
              <% end %>
              <td class="text-right">
                <a class="btn btn-default" href="<%= logo.png_url + '!' + thumb.ext %>" role="button" target="_blank">下载PNG</a>
                &nbsp &nbsp
                <a class="btn btn-default" href="<%= logo.jpg_url + '!' + thumb.ext %>" role="button" target="_blank">下载JPG</a>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  <% end %>


</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="http://cdn.bootcss.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="ie10-viewport-bug-workaround.js"></script>
</body>
</html>